### ISSUE TITLE
Special Character encoding not working

### ISSUE THREAD

**Issue by katerlouis** [huntie/super-awesome-paste#1]
I can't get the special character encoding to work.
Although the other features are nice aswell, encoding while pasting is what I intended to use this plugin for.

"super_awesome_paste.escape_html": true
is in the preferences.sublime-settings file and I restarted sublime settings so far.
The plugin seems to work, as the pasted text has sweet indentation. 

I'd appreciate some help!

**Comment by huntie** [comment]
Hey there. A while since I've done anything with this project, but I really intend to document these things better.

HTML character escaping is selective. Currently, it will only apply when a plain text string is pasted inside an HTML content tag matching the regular expression below ([source](https://github.com/huntie/super-awesome-paste/blob/v1.2.2/util.py#L50)).

```
p|h[1-6]|span|em|strong|a|small|td
```

This was intended to limit the functionality until it was needed, but even then sometimes, for instance, I've been pasting into Handlebars tags inside these contexts and not wanted quotes escaped. So recently I've been wondering if this kind of paste modification should be on by default, or made even less aggressive. Alternatively, the plugin could provide HTML character escaping as a separate bindable command for the user to choose. What do you think?

**Comment by katerlouis** [comment]
I didn't really get the reg exp part, but I'd love to have a command for: "Paste and encode html entities".

Off-topic:
how did you make it happen, that text is indented but is displayed as part of the same line as the one before?

That's really nice!
<img width="1159" alt="920b01e2-040a-4556-9962-3eaae22f7603" src="https://cloud.githubusercontent.com/assets/1983382/16358209/7daf2316-3b0d-11e6-8709-1e91dc7e4b11.png">

**Comment by huntie** [comment]
Cool, I think a separate command makes sense. Should have time to work on it tomorrow.

The text wrapping in the line pictured is a feature of Sublime itself. When `Word Wrap` is enabled, it does smart text wrapping in some languages. This plugin only ensures that when you paste in any file, the result will be auto indented first ;)

**Comment by katerlouis** [comment]
Nice! Although I had some problems after pasting something outside of a pdf with backgrounds.
There is an additional whitespace at the beginning.
And how comes the first line has a line-break at the begining so a new line in sublime text begins?
This is almost always the case.

<img width="697" alt="90cb98c9-51d4-4374-8dfc-12d130a7110d" src="https://cloud.githubusercontent.com/assets/1983382/16358295/6e56bdb4-3b0f-11e6-9f8b-db18c1b8c493.png">

![851e6b6a-d9ff-4af4-9633-3b5520c66963](https://cloud.githubusercontent.com/assets/1983382/16358297/70307332-3b0f-11e6-90dd-879eddf5f62c.png)

**Comment by huntie** [comment]
Pretty sure that much is to do with the PDF format I'm afraid. Sometimes I even get double newlines on Windows, and removing these is not a safe operation to attempt on every paste.

That does give me a new feature idea though: Configurable after-paste hooks

**Comment by katerlouis** [comment]
I'm looking forward to it and watch out for an update. Hopefully soon!

**Comment by huntie** [comment]
@katerlouis Changes are now in and the release should be live through Package Control soon.

![image](https://cloud.githubusercontent.com/assets/2547783/16463652/a22a8ba8-3e2e-11e6-9358-60f8647eaa11.png)

'Paste and HTML encode' has been added as a new context menu option, and the regular paste command will no longer attempt to do this. Selecting the new option will now always encode any special characters into escaped HTML entities, without the checks that were there before.

The option `escape_html` has subsequently now been removed.

All changes are non-breaking and the main command name remains the same. I'll be back soon for more active development on this project again, starting with clearer and more detailed documentation. :)

**Comment by katerlouis** [comment]
Nice! Thank you!
I'm looking forward to more documentation, because I'm confused :)

Quick pitch of what I am looking for:
Sometimes I wanna paste with encoded entities, sometimes not. 
I'm a keyboard evangelist, so browsing dropdowns by mouse is not an option for me. 
So access to both functions without changing a setting would be nice.
I imagine 2 separate commands, which the user can bind to whatever they want.

If you want to pre-bind with your plugin, how about that: 
you prebind the unescaped command and make a setting called "use_escaped_instead" for those who are cool with your shortcut and just want to the plugin to work. They don't want to bother with binding a command in user-keymap bla; so they can set "use_escaped_instead", which simply internally binds the new command to your pre-bound key.

And maybe a third command: "super_awesome_paste_toggled"
If I want to have the same shortcut for awesome paste all the time but still wanna be able to switch between encoded and unencoded quickly. Switching through a context item or setting or better: a control panel item

I also suggest providing control panel items. I literally use it for everything. It's auto completion is insanely clever. Item suggestion: 
– "Super Awesome Paste: paste HTML encoded"
– "Super Awesome Paste: paste plain"
– "Super Awesome Paste: Toggle encoding"

**Comment by katerlouis** [comment]
Oh :( – I see the new context item, but hitting it still pastes with "ü, ä, ö" etc.

<img width="471" alt="02270977-dd10-4711-817f-0111611abc7a" src="https://cloud.githubusercontent.com/assets/1983382/16484481/b0fa9d7c-3eb9-11e6-8e76-9ea9d82cae38.png">

**Comment by huntie** [comment]
Hey again. Sure, you can bind the command with the `html_encode` argument enabled to a key combination right now – add something like the below to your default keymap file:

``` json
{ "keys": ["super+alt+shift+v"], "command": "super_awesome_paste", "args": { "html_encode": true } },
```

[Source reference](https://github.com/huntie/super-awesome-paste/blob/master/Menus/Context.sublime-menu) for context menu bindings you can match. More documentation needed again!

Command palette support is **_absolutely**_ coming up :)

As for the characters that get encoded, this currently uses Python's `html.escape` method, which only escapes a subset of characters that need to be escaped in UTF-8. I'll look into if this is sufficient though.

**Comment by katerlouis** [comment]
Oh. Too bad,
I need the complete opposite. I don't want to escape html code when pasting. I paste special characters like "ü, ä, ö, é, ß" 
And how about – (ndash) etc.?

Idea: use sublime text build in command `"encode_html_entities"`

Even further:
since I use a plugin for these jobs (SublimeStringEncode) I'd love to use their encoding. So how about an option in SAP

``` php
"sap_encoding_command": "encode_html_entities"
```

Where I can simply include my own:

``` json
{ "sap_encoding_command": "safe_html_entitize" }
```

**Comment by huntie** [comment]
I'll investigate using Sublime's built-in command — now this is separate it ought to escape more things. The above snippet was suggested for a _second_ key binding, and works now.

What you then suggest would be a general `after_paste` hook idea which I hinted at on Saturday — a way to run additional command logic. On my to do list!

**Comment by katerlouis** [comment]
Yeah, args for the same command would be fine with me :D
I actually don't care how the pie is made, I just wanna eat it ;)
An option inside the args for the actual encoding function would still be nice.
When will the pie be ready? I have to paste and encode a lot the next days 8)

**Comment by katerlouis** [comment]
Oh, and how about optional `"join_lines"` as one of these famous after hooks, whatever they may be! :D
